trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  AZURE_PAT: $(azurePat)
  GITHUB_PAT: $(githubPat)

steps:
- script: |
    git config --global user.email "lbs3kor@bosch.com"
    git config --global user.name "lbs3kor"

    # Clone Azure DevOps Repo
    git clone https://$(AZURE_PAT)@dev.azure.com/lbs3kor/demo5/_git/demo5-repo azure-repo

    cd azure-repo

    # Add GitHub as remote using PAT
    git remote add github https://$(GITHUB_PAT)@github.com/lbs3kor/java_application.git
    git fetch github

    # Create main branch if not exists
    git checkout -b main
    git pull github main --allow-unrelated-histories

    # Push to Azure DevOps
    git push origin main
  displayName: 'Sync GitHub to Azure Repos'
