trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self  # Make sure to checkout the GitHub code
  fetchDepth: 0

- script: echo Hello, world!
    echo "Listing files in repository:"
    ls -la
  displayName: 'List checked out files'
