trigger:
  branches:
    include:
    - main
    - master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0
  clean: true
  persistCredentials: true

# Verification step (keep this for debugging)
- script: |
    echo "Current Git status:"
    git status
    echo "Current branch and commit:"
    git branch
    git log -1
    echo "Files in repository:"
    ls -la
  displayName: 'Verify checkout'

# This step syncs GitHub changes to Azure DevOps repo
- script: |
    git config --global user.email "pipeline@example.com"
    git config --global user.name "Azure Pipeline"
    
    # Add Azure DevOps repo as a remote (replace with your actual repo URL)
    echo "Adding Azure DevOps repo as remote..."
    git remote add ado https://$(System.AccessToken)@dev.azure.com/lbs3kor/demo5/_git/demo5
    
    # Push the current state to Azure DevOps
    echo "Pushing changes to Azure DevOps..."
    git push ado HEAD:$(Build.SourceBranchName) -f
  displayName: 'Sync to Azure DevOps Repository'
  env:
    System.AccessToken: $(System.AccessToken)

# Your actual build steps
- script: echo "Building files from commit $(Build.SourceVersion)"
  displayName: 'Build step'