trigger:
- main  # or your GitHub branch

pool:
  vmImage: ubuntu-latest

variables:
  AZURE_PAT: $(azurePat)  # This will be passed as a secret variable

steps:
- checkout: self

- script: |
    git config --global user.email "lbs3kor@bosch.com"
    git config --global user.name "lbs3kor"

    # Clone the Azure DevOps Repo using PAT
    git clone https://$(uDXSWtVGEJe7T0meK6tvhJsT4YJWLgtJsN6vhM0KsbHB68FQrJw9JQQJ99BDACAAAAAg9ApBAAASAZDO3wJx)@dev.azure.com/lbs3kor/demo5/_git/https://dev.azure.com/lbs3kor/_git/demo5 azure-repo

    cd azure-repo

    # Pull latest from GitHub
    git remote add github https://github.com/lbs3kor/java_application.git
    git fetch github
    git merge github/main --allow-unrelated-histories -m "Sync from GitHub"

    # Push to Azure DevOps Repo
    git push origin main
  displayName: 'Sync GitHub to Azure Repos'
