trigger:
  branches:
    include:
    - main
    - master  # Include both main and master for compatibility

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0
  clean: true  # This ensures a clean checkout
  persistCredentials: true  # This allows Git commands to run after checkout

# Verify what we've checked out
- script: |
    echo "Current Git status:"
    git status
    echo "Current branch and commit:"
    git branch
    git log -1
    echo "Files in repository:"
    ls -la
    git remote -v
    git fetch --all
    git reset --hard origin/main
    git status
  displayName: 'Verify checkout'

# Your actual build steps would go here
- script: echo "Building files from commit $(Build.SourceVersion)"
  displayName: 'Build step'