# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
